### ISSUE TITLE
Save the signal to a file

### ISSUE THREAD

**Issue by paryska99** [antirez/protoview#2]
Hi, would you consider adding a feature allowing to save the signals to a file similary to the main sub-ghz app? Looking at the protocol pattern and figuring out if the signal looks somewhat proper is way nicer than just blindly shooting into the original app. Thank you for your time and the project.

**Comment by antirez** [comment]
Thank you. It's a planned feature, with the ability to save the signal normalized and filtered using the data rate auto detected. This was it is possible to analyze offline and reply with subghz. Another thing I would like to implement in this context is the ability to generate a file with the signal copied N times but with a few bit errors in each copy as a fuzzer.

**Comment by antirez** [comment]
Closing since now this is part of the official roadmap and no need for a reminder :) Thanks!
